Query multiple tables
JacintaNgwu/Vet-clinic-database pull request #3
Opened 2023-03-01 21:35 UTC by JacintaNgwu

- What animals belong to Melody Pond?
![image](https://user-images.githubusercontent.com/100554236/222268827-f2323eac-316c-4e65-bc7a-92bd5f2f5f11.png)

- List of all animals that are pokemon (their type is Pokemon).
![image](https://user-images.githubusercontent.com/100554236/222269012-cdbebeef-2183-4c89-bea6-d6a899167f9d.png)

- List all owners and their animals, remember to include those that don't own any animal.
![image](https://user-images.githubusercontent.com/100554236/222269179-0b187d81-a95f-40a0-83a3-adefa153cac6.png)

- How many animals are there per species?
![image](https://user-images.githubusercontent.com/100554236/222269325-67217943-a9f8-4ca2-bfe0-2da5c8fbd7a8.png)

- List all Digimon owned by Jennifer Orwell.
![image](https://user-images.githubusercontent.com/100554236/222269497-eb35007a-1b34-45bf-8df8-263586cdd123.png)

- List all animals owned by Dean Winchester that haven't tried to escape.
![image](https://user-images.githubusercontent.com/100554236/222269661-a10640c4-360a-4f60-81b1-f34bd991201f.png)

- Who owns the most animals?
![image](https://user-images.githubusercontent.com/100554236/222269816-b7d1cb18-8e52-42da-9adf-545d54a9408e.png)

2023-03-01 22:32 UTC, Gambit142 requested changes
Hi @JacintaNgwu 👋 , 

Good job so far!

## Highlights
- Everything that creates or changes the structure of the tables is in the _**schema.sql**_ file
- Everything that populates tables with data is in the _**data.sql**_ file
- Everything that is a query that helps to analyze data is in the _**queries.sql**_ file

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +WHERE owners.full_name = 'Melody Pond';
- [ ] One of the requirements is that you include the snapshot of queries in your pull request summary. The snapshot for the result of this query is incorrect. Kindly include the correct snapshot. 👍

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +WHERE species.name = 'Pokemon';
- [ ] One of the requirements is that you include the snapshot of queries in your pull request summary. The snapshot for the result of this query is incorrect. Kindly include the correct snapshot. 👍

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +LEFT JOIN animals ON owners.id = animals.owner_id;
- [ ] One of the requirements is that you include the snapshot of queries in your pull request summary. The snapshot for the result of this query is incorrect. Kindly include the correct snapshot. 👍

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +
- [ ] The query gives the wrong result. The correct query should bring the total number of _**Digimons**_ and the total number of _**Pokemons**_. Kindly write the correct query and update the screenshot. 👍 

Hint: When creating the `animals` table, that `ID` was not serial, so your current `animals` table has no data for ID. So, I would advise you to either make the `ID` serial or change `count(animals.id)` to `count(animals.species_id)`. 👍 😎

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +WHERE species.name = 'Digimon' AND owners.full_name = 'Jennifer Orwell';
- [ ] One of the requirements is that you include the snapshot of queries in your pull request summary. The snapshot for the result of this query is incorrect. Kindly include the correct snapshot. 👍

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +
- [ ] One of the requirements is that you include the snapshot of queries in your pull request summary. The snapshot for the result of this query is incorrect. Kindly include the correct snapshot. 👍

2023-03-01 22:32 UTC, Gambit142 commented on queries.sql
> +LIMIT 1;
- [ ] The query gives the wrong result. The correct query should give the name and number of animals of the person that owns the most animals. 👍 

Hint: When creating the `animals` table, that `ID` was not serial, so your current `animals` table has no data for ID. So, I would advise you to either make the `ID` serial or change `count(animals.id)` to `count(animals.species_id)`. 👍 😎

2023-03-02 09:49 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @JacintaNgwu 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.
- Your linters are passing all the checks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 09:50 UTC, merged